package dev.jemyz.pingguard;

// GENERATED by tools/gen_assets.py - do not edit by hand.
public final class CardLayout {
	private CardLayout() {
	}

	/** Frames per second of the card animation. */
	public static final int FPS = 10;
	/** Unique frames in card_frames.png (stacked vertically). */
	public static final int FRAME_COUNT = 23;
	/** step -> frame index; one step = 1/FPS s. */
	public static final int[] TIMELINE = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 15, 16, 17, 15, 16, 17, 15, 16, 17, 15, 16, 17, 18, 19, 20, 21, 21, 21, 22, 22, 22, 21, 21, 21, 22, 22, 22, 21, 21, 21, 22, 22};

	/** Title-glyph code points (font pingguard:card). */
	public static final int FRAME_CHAR0 = 0xE000;
	public static final int BAND_CHAR = 0xE100;
	public static final int LINE1_CHAR0 = 0xE110;
	public static final int LINE1_CHUNKS = 2;
	public static final int LINE1_CHUNK_FU = 12;
	public static final int LINE2_CHAR0 = 0xE120;
	public static final int LINE2_CHUNKS = 3;
	public static final int LINE2_CHUNK_FU = 14;
	public static final int SIGNAL_POOR = 0xE200;
	public static final int SIGNAL_BAD = 0xE201;
	public static final int SIGNAL_LOST = 0xE202;
	/** Space glyph code point for an advance (font pingguard:card / pingguard:icons). */
	public static int spaceChar(int advance) {
		return switch (advance) {
			case -1 -> 0xF800;
			case -2 -> 0xF801;
			case -4 -> 0xF802;
			case -8 -> 0xF803;
			case -16 -> 0xF804;
			case -32 -> 0xF805;
			case -64 -> 0xF806;
			case 1 -> 0xF807;
			case 2 -> 0xF808;
			case 4 -> 0xF809;
			case 8 -> 0xF80A;
			case 16 -> 0xF80B;
			case 32 -> 0xF80C;
			case 64 -> 0xF80D;
			default -> throw new IllegalArgumentException("no space glyph for " + advance);
		};
	}

	/** Geometry in title font units (1 fu = 4 GUI px), relative to the screen centre. */
	public static final int CARD_W = 44;
	public static final int SCENE_H = 22;
	public static final int BAND_H = 8;
	public static final int CARD_TOP = -15;
	public static final int TEXT_BOX_H = 3;
	public static final int LINE1_TOP = 8;
	public static final int LINE2_TOP = 11;
	public static final int LINE1_W = 24;
	public static final int LINE2_W = 42;

	/** Alpha (out of 255) at which an armed card becomes visible; see text.vsh. */
	public static final int REVEAL_ALPHA = 11;
	/** Fade length used as the shader clock; alpha changes by exactly 1 every 2 ticks. */
	public static final int CLOCK_TICKS = 510;
}
